---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "https://trmnl.1a23.workers.dev/zi-tools?compress{{ qps }}\r\nhttps://usetrmnl.com/custom_plugin_example_data.json"
polling_headers: ''
polling_body: ''
id: 156095
custom_fields:
- keyname: doesnt_matter
  name: About This Plugin
  field_type: author_bio
  description: A random CJKV ideograph (Chinese characters, Hanzi, Kanji, Hanja, Chữ Nôm) with pronunciations, definitions, and regional glyphs on each refresh. Data powered by <a href="https://zi.tools/">zi.tools 字統网</a>.
  github_url: https://github.com/blueset/trmnl-recipes
  learn_more_url: https://zi.tools/
- keyname: qps
  field_type: select
  options:
  - Default chance: ''
  - Increase chance of rare ideograph in random: "&rare"
  default: ''
  name: Random selection mode
name: Random Zi
refresh_interval: 15
