---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://blueset.github.io/wikipedia-featured/visa_bulletin.json
polling_headers: ''
polling_body: ''
id: 155086
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
  description: <a href="https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html">U.S. Department of State Visa Bulletin</a> tracker.
  category: analytics,personal
  github_url: https://github.com/blueset/trmnl-recipes
- keyname: category
  field_type: select
  name: Category
  options:
  - Certain Religious Workers: Certain Religious Workers
  - EB-1: EB-1
  - EB-2: EB-2
  - EB-3: EB-3
  - EB-4: EB-4
  - EB-5 Non-Regional Center: EB-5 Non-Regional Center
  - EB-5 Regional Center: EB-5 Regional Center
  - 'EB-5 Set Aside: High Unemployment': 'EB-5 Set Aside: High Unemployment'
  - 'EB-5 Set Aside: Infrastructure': 'EB-5 Set Aside: Infrastructure'
  - 'EB-5 Set Aside: Rural': 'EB-5 Set Aside: Rural'
  - EB-5 Unreserved: EB-5 Unreserved
  - F1: F1
  - F2-A: F2-A
  - F2-B: F2-B
  - F3: F3
  - F4: F4
  - Other Workers: Other Workers
- keyname: region
  field_type: select
  name: Region
  options:
  - CHINA-mainland born: cn
  - INDIA: ind
  - MEXICO: mex
  - PHILIPPINES: phl
- keyname: look_back_months
  field_type: number
  name: Look back months
  placeholder: '24'
  default: '24'
  min: 0
  max: 48
- keyname: target_date
  field_type: date
  name: Target date
name: Visa Bulletin
refresh_interval: 1440
